# Main Imports

In [36]:
import os
import pandas as pd 
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np
from tqdm import tqdm
from collections import defaultdict
import statsmodels.formula.api


pd.options.display.max_columns = 200
pd.options.display.max_rows = 50

In [37]:
raw_path = '../database/raw/faj2015-2020.csv'

raw = pd.read_csv(raw_path,index_col=0)

In [38]:
for i in raw:
    raw[i] = raw[i].replace("nd",np.nan).str.replace(",", '.').astype(float)

In [39]:
raw.dtypes

Budget FAJ (en euros)                                                        float64
Montant des aides individuelles attribuées (en euros)                        float64
Nombre d'aides individuelles attribuées (2)                                  float64
Montant moyen de l'aide individuelle attribuée (en euros)                    float64
Nombre de bénéficiaires du FAJ                                               float64
Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %    float64
Population étudiante                                                         float64
Taux pauvreté département                                                    float64
Population étudiante sous le seuil de pauvreté                               float64
dtype: object

In [40]:
cleaned_path = "../database/cleaned/cleaned_faj2015_2020.csv"

raw.to_csv(cleaned_path)

# Load cost rent student csv

In [41]:
rent_csv_path = "../database/raw/rent_cost_student.csv"

rent_df = pd.read_csv(rent_csv_path,index_col=0)

# Reindex but getting rid of numbers of departments

In [42]:
rent_df.columns
new_index = [i[5:] for i in rent_df.index]
rent_df.index = new_index
rent_df

                        Loyer m2 moyen\r\nappartement Loyer m2 moyen\r\nmaison
Ain                                            13,60€                   13,70€
Aisne                                          11,10€                   10,10€
Allier                                         10,80€                    9,80€
Alpes-de-Haute-Provence                        11,70€                   11,40€
Hautes-Alpes                                   12,00€                   12,50€
...                                               ...                      ...
Guadeloupe                                     12,00€                   13,00€
Martinique                                     12,00€                   13,00€
Mayotte                                        13,00€                   13,00€
Guyane                                         13,00€                   14,00€
La Réunion                                     10,00€                   12,00€

[101 rows x 2 columns]

# Fix columns \n element

In [43]:
rent_df.columns = [i.replace('\n', ' ') for i in rent_df.columns]

In [44]:
rent_df

                        Loyer m2 moyen\r appartement Loyer m2 moyen\r maison
Ain                                           13,60€                  13,70€
Aisne                                         11,10€                  10,10€
Allier                                        10,80€                   9,80€
Alpes-de-Haute-Provence                       11,70€                  11,40€
Hautes-Alpes                                  12,00€                  12,50€
...                                              ...                     ...
Guadeloupe                                    12,00€                  13,00€
Martinique                                    12,00€                  13,00€
Mayotte                                       13,00€                  13,00€
Guyane                                        13,00€                  14,00€
La Réunion                                    10,00€                  12,00€

[101 rows x 2 columns]

# Convert series from object to float

In [45]:
for i in rent_df:
    rent_df[i] = rent_df[i].str.replace('€','').str.replace(',', '.').astype(float)

rent_df

                         Loyer m2 moyen\r appartement  Loyer m2 moyen\r maison
Ain                                              13.6                     13.7
Aisne                                            11.1                     10.1
Allier                                           10.8                      9.8
Alpes-de-Haute-Provence                          11.7                     11.4
Hautes-Alpes                                     12.0                     12.5
...                                               ...                      ...
Guadeloupe                                       12.0                     13.0
Martinique                                       12.0                     13.0
Mayotte                                          13.0                     13.0
Guyane                                           13.0                     14.0
La Réunion                                       10.0                     12.0

[101 rows x 2 columns]

In [46]:
rent_df.dtypes

Loyer m2 moyen\r appartement    float64
Loyer m2 moyen\r maison         float64
dtype: object

# Save cleaned DF

In [47]:
path_cleaned = "../database/cleaned/cleaned_rent_cost_student.csv"

rent_df.to_csv(path_cleaned)

# Load FAJ 2015 2020

In [48]:
path_df = "../database/cleaned/cleaned_faj2015_2020.csv"

faj_df = pd.read_csv(path_df, index_col=0)

In [49]:
faj_df

,Budget FAJ (en euros),Montant des aides individuelles attribuées (en euros),Nombre d'aides individuelles attribuées (2),Montant moyen de l'aide individuelle attribuée (en euros),Nombre de bénéficiaires du FAJ,Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %,Population étudiante,Taux pauvreté département,Population étudiante sous le seuil de pauvreté
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480
...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,34.5,3313.000
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,53.0,2252.000
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,77.0,1274.000

# Cost rent

In [50]:
path_df = "../database/cleaned/cleaned_rent_cost_student.csv"

cost_rent_df = pd.read_csv(path_df, index_col=0)

In [51]:
for i in faj_df.index:
    if i not in cost_rent_df.index:
        print('Dieu', i)

In [52]:
for i in faj_df.index:
    if i not in cost_rent_df.index:
        print('Dieu', i)

In [53]:
cost_rent_df.loc["Ain",["Loyer m2 moyen\r appartement","Loyer m2 moyen\r maison"]][0]

C:\Users\james\AppData\Local\Temp\ipykernel_17616\2615587039.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cost_rent_df.loc["Ain",["Loyer m2 moyen\r appartement","Loyer m2 moyen\r maison"]][0]

np.float64(13.6)

In [54]:
cost_arr_appartement = []
cost_arr_maison = []

for i in faj_df.index:
    if i in cost_rent_df.index:
        cost_arr_appartement.append(cost_rent_df.loc[i,["Loyer m2 moyen\r appartement"]].values[0])
        cost_arr_maison.append(cost_rent_df.loc[i,["Loyer m2 moyen\r maison"]].values[0])
    else:
        cost_arr_appartement.append(np.nan)
        cost_arr_maison.append(np.nan)

In [55]:
cost_arr_appartement
cost_arr_maison

[np.float64(13.7),
 np.float64(9.8),
 np.float64(11.0),
 np.float64(9.7),
 np.float64(11.9),
 np.float64(13.4),
 np.float64(10.8),
 np.float64(9.8),
 np.float64(10.7),
 np.float64(15.0),
 np.float64(13.2),
 np.float64(18.4),
 np.float64(11.6),
 np.float64(12.4),
 np.float64(11.3),
 np.float64(9.7),
 np.float64(9.7),
 np.float64(10.2),
 np.float64(10.6),
 np.float64(12.1),
 np.float64(10.2),
 np.float64(11.1),
 np.float64(11.5),
 np.float64(11.8),
 np.float64(9.8),
 np.float64(11.8),
 np.float64(9.0),
 np.float64(11.2),
 np.float64(10.0),
 np.float64(11.5),
 np.float64(13.9),
 np.float64(14.0),
 np.float64(9.5),
 np.float64(10.6),
 np.float64(11.0),
 np.float64(9.2),
 np.float64(11.3),
 np.float64(9.3),
 np.float64(11.7),
 np.float64(12.3),
 np.float64(13.3),
 np.float64(10.0),
 np.float64(10.1),
 np.float64(11.2),
 np.float64(13.2),
 np.float64(10.8),
 np.float64(10.5),
 np.float64(28.4),
 np.float64(16.0),
 np.float64(20.1),
 np.float64(18.4),
 np.float64(28.5),
 np.float64(20.7),
 np.float64(23.4),
 np.float64(19.4),
 np.float64(12.0),
 np.float64(11.8),
 np.float64(10.0),
 np.float64(9.2),
 np.float64(12.0),
 np.float64(9.6),
 np.float64(11.7),
 np.float64(9.9),
 np.float64(8.9),
 np.float64(9.9),
 np.float64(13.3),
 np.float64(11.8),
 np.float64(10.0),
 np.float64(12.9),
 np.float64(9.3),
 np.float64(9.8),
 np.float64(9.6),
 np.float64(9.7),
 np.float64(10.5),
 np.float64(10.3),
 np.float64(11.6),
 np.float64(12.5),
 np.float64(10.3),
 np.float64(12.7),
 np.float64(9.9),
 np.float64(9.7),
 np.float64(10.7),
 np.float64(11.1),
 np.float64(10.3),
 np.float64(10.7),
 np.float64(12.2),
 np.float64(10.6),
 np.float64(9.0),
 np.float64(9.5),
 np.float64(11.1),
 np.float64(11.4),
 np.float64(12.5),
 np.float64(19.8),
 np.float64(15.8),
 np.float64(15.0),
 np.float64(12.5),
 np.float64(13.0),
 np.float64(13.0),
 np.float64(14.0),
 np.float64(12.0),
 np.float64(13.0)]

In [56]:
faj_df["Loyer moyen m2 appartement"] = cost_arr_appartement
faj_df["Loyer moyen m2 maison"] = cost_arr_maison

In [57]:
faj_df

,Budget FAJ (en euros),Montant des aides individuelles attribuées (en euros),Nombre d'aides individuelles attribuées (2),Montant moyen de l'aide individuelle attribuée (en euros),Nombre de bénéficiaires du FAJ,Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %,Population étudiante,Taux pauvreté département,Population étudiante sous le seuil de pauvreté,Loyer moyen m2 appartement,Loyer moyen m2 maison
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215,13.6,13.7
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121,10.8,9.8
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345,10.4,11.0
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892,9.6,9.7
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480,11.3,11.9
...,...,...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,34.5,3313.000,12.0,13.0
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676,12.0,13.0
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,53.0,2252.000,13.0,14.0
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656,10.0,12.0
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,77.0,1274.000,13.0,13.0

# Merge Energy consumption

In [58]:
path_df = "../database/cleaned/consommation_energetique.csv"
energy_df = pd.read_csv(path_df)
energy_df.dtypes

Consommation energetique Departement (Mwh)    float64
Population departement                          int64
dtype: object

In [59]:
consomme_moyen = []
for i in energy_df.index:
    consomme_moyen.append(energy_df.loc[i][0]/energy_df.loc[i][1])
consomme_moyen

C:\Users\james\AppData\Local\Temp\ipykernel_17616\2035336234.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  consomme_moyen.append(energy_df.loc[i][0]/energy_df.loc[i][1])

[np.float64(4.395063689979555),
 np.float64(5.073961465404198),
 np.float64(3.6967387618657255),
 np.float64(3.4349827922662923),
 np.float64(4.125585521247786),
 np.float64(3.888683306265823),
 np.float64(4.3591531167564295),
 np.float64(3.947151151567364),
 np.float64(4.444951565799846),
 np.float64(4.2199306556882235),
 np.float64(4.4066431874876635),
 np.float64(4.587153652227175),
 np.float64(4.688141749251642),
 np.float64(3.9884778443200126),
 np.float64(4.053572750470985),
 np.float64(4.92083183654346),
 np.float64(3.635555187761642),
 np.float64(5.216047112948083),
 np.float64(5.012917071167538),
 np.float64(4.654387936966665),
 np.float64(4.009124723293404),
 np.float64(3.9917090840715175),
 np.float64(3.8883995113230965),
 np.float64(4.1639577911742425),
 np.float64(4.995884759806269),
 np.float64(4.790510872569493),
 np.float64(4.595795194721248),
 np.float64(4.399662268616724),
 np.float64(4.713925296543082),
 np.float64(4.792323553773391),
 np.float64(3.19265549019364),
 np.float64(2.8831626031374564),
 np.float64(5.01280441201208),
 np.float64(4.505282850243133),
 np.float64(4.57668169095223),
 np.float64(4.205304453044593),
 np.float64(5.582982634276854),
 np.float64(4.485329394204885),
 np.float64(5.818487502617916),
 np.float64(3.9426941641490307),
 np.float64(4.737879743952076),
 np.float64(4.6696069440041725),
 np.float64(4.549899145347033),
 np.float64(5.20075822070635),
 np.float64(4.358168821327397),
 np.float64(5.012171949716756),
 np.float64(4.202094126024233),
 np.float64(4.23091799397097),
 np.float64(4.678510260511873),
 np.float64(4.901596841603534),
 np.float64(4.487988545993119),
 np.float64(4.159671334259768),
 np.float64(3.583580277726253),
 np.float64(3.88829747004145),
 np.float64(4.278317175504216),
 np.float64(4.55730897684179),
 np.float64(4.330942258635112),
 np.float64(4.227619455309952),
 np.float64(3.9652210729965707),
 np.float64(4.282592571433215),
 np.float64(4.529789278992403),
 np.float64(4.55740239983697),
 np.float64(4.4072801010529705),
 np.float64(3.736153074985465),
 np.float64(4.44477052093402),
 np.float64(4.558629671097232),
 np.float64(4.247058096929772),
 np.float64(4.282431143504492),
 np.float64(4.568271150262543),
 np.float64(3.8158248879403227),
 np.float64(3.892350447764447),
 np.float64(4.46842895719848),
 np.float64(4.428688679604947),
 np.float64(4.032287768513527),
 np.float64(3.922491271112057),
 np.float64(4.199117752525335),
 np.float64(4.208324318598615),
 np.float64(3.8818914089131993),
 np.float64(3.9291011188166087),
 np.float64(3.8641615022515543),
 np.float64(2.5897449773761045),
 np.float64(5.303939954157745),
 np.float64(3.749517991343759),
 np.float64(4.119928552629454),
 np.float64(3.8968940592518186),
 np.float64(4.195028859243502),
 np.float64(3.779850454089493),
 np.float64(3.8223447584065595),
 np.float64(4.321670783038379),
 np.float64(4.023676607599064),
 np.float64(3.9982416908108864),
 np.float64(4.264700417802382),
 np.float64(4.769783651913433),
 np.float64(3.59961889656957),
 np.float64(4.071634232674225),
 np.float64(4.072030184371153),
 np.float64(1.8835149351208027),
 np.float64(1.6881780192400857),
 np.float64(1.1251099872690988),
 np.float64(1.4740968307798903),
 np.float64(0.6663533722327099)]

In [60]:
faj_df["Consommation énergétique moyenne (MWh)"] = consomme_moyen

# Add median income per department

In [61]:
path_df = "../database/cleaned/niveau de vie médian.csv"
money_df = pd.read_csv(path_df)
money_df.dtypes

Niveau de vie median    float64
dtype: object

In [62]:
niveau_median = []
for i in money_df.index:
    niveau_median.append(float(money_df.loc[i][0]))
niveau_median

C:\Users\james\AppData\Local\Temp\ipykernel_17616\3913514954.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  niveau_median.append(float(money_df.loc[i][0]))

[24030.0,
 20990.0,
 21450.0,
 21140.0,
 21790.0,
 23580.0,
 21380.0,
 21470.0,
 22510.0,
 23690.0,
 23630.0,
 27030.0,
 22940.0,
 23260.0,
 22460.0,
 20940.0,
 21260.0,
 21520.0,
 21390.0,
 22370.0,
 21850.0,
 22400.0,
 22840.0,
 22270.0,
 21560.0,
 22650.0,
 20820.0,
 22450.0,
 21940.0,
 22480.0,
 22350.0,
 20740.0,
 20310.0,
 20960.0,
 22230.0,
 20780.0,
 22400.0,
 21320.0,
 22350.0,
 23330.0,
 23760.0,
 20900.0,
 20300.0,
 20750.0,
 22680.0,
 20090.0,
 20980.0,
 28790.0,
 24000.0,
 27470.0,
 24410.0,
 28810.0,
 18470.0,
 23540.0,
 22650.0,
 22180.0,
 22240.0,
 21740.0,
 20800.0,
 21700.0,
 21410.0,
 22080.0,
 21590.0,
 20130.0,
 20830.0,
 23180.0,
 22100.0,
 20550.0,
 22550.0,
 21590.0,
 21580.0,
 21610.0,
 20430.0,
 19980.0,
 21260.0,
 20740.0,
 23730.0,
 21420.0,
 21130.0,
 21310.0,
 20940.0,
 20990.0,
 20070.0,
 21080.0,
 20860.0,
 23430.0,
 21790.0,
 21510.0,
 21630.0,
 22040.0,
 21130.0,
 21420.0,
 22630.0,
 22210.0,
 22320.0,
 20640.0,
 18000.0,
 19200.0,
 11000.0,
 16520.0,
 9000.0]

In [63]:
faj_df["Niveau de vie median"] = niveau_median
faj_df

,Budget FAJ (en euros),Montant des aides individuelles attribuées (en euros),Nombre d'aides individuelles attribuées (2),Montant moyen de l'aide individuelle attribuée (en euros),Nombre de bénéficiaires du FAJ,Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %,Population étudiante,Taux pauvreté département,Population étudiante sous le seuil de pauvreté,Loyer moyen m2 appartement,Loyer moyen m2 maison,Consommation énergétique moyenne (MWh),Niveau de vie median
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215,13.6,13.7,4.395064,24030.0
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121,10.8,9.8,5.073961,20990.0
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345,10.4,11.0,3.696739,21450.0
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892,9.6,9.7,3.434983,21140.0
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480,11.3,11.9,4.125586,21790.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,34.5,3313.000,12.0,13.0,1.883515,18000.0
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676,12.0,13.0,1.688178,19200.0
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,53.0,2252.000,13.0,14.0,1.125110,11000.0
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656,10.0,12.0,1.474097,16520.0
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,77.0,1274.000,13.0,13.0,0.666353,9000.0

# Save merged df

In [64]:
path_merged = "../database/cleaned/merged_faj2015_2020.csv"
faj_df.to_csv(path_merged)

In [65]:

df = pd.DataFrame({'x1': [2, 6, 7, 8, 6, 2], 'x2': [4, 2, 9, 1, 7, 2]})
df['y'] = df['x1'] * 2 + df['x2'] * 5 + 0.2 * np.random.randn(len(df)) + 3
model = statsmodels.formula.api.ols('y ~ x1 + x2', data = df)
result = model.fit()

In [66]:
result.summary()

c:\Users\james\Documents\french_student_precariousness_in_conometrics\.venv\Lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.401e+04
Date:                Mon, 18 Nov 2024   Prob (F-statistic):           1.11e-06
Time:                        09:42:06   Log-Likelihood:                 2.2706
No. Observations:                   6   AIC:                             1.459
Df Residuals:                       3   BIC:                            0.8340
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.4141      0.252     13.551      0.001       2.612       4.216
x1             1.9674      0.042     47.205      0.000       1.835       2.100
x2             4.9765      0.033    148.573      0.000       4.870       5.083
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.068
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.448
Skew:                          -0.268   Prob(JB):                        0.799
Kurtosis:                       1.774   Cond. No.                         19.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [67]:
faj_path = "../database/cleaned/merged_faj2015_2020.csv"

faj_df = pd.read_csv(faj_path, index_col=0)
faj_df

,Budget FAJ (en euros),Montant des aides individuelles attribuées (en euros),Nombre d'aides individuelles attribuées (2),Montant moyen de l'aide individuelle attribuée (en euros),Nombre de bénéficiaires du FAJ,Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %,Population étudiante,Taux pauvreté département,Population étudiante sous le seuil de pauvreté,Loyer moyen m2 appartement,Loyer moyen m2 maison,Consommation énergétique moyenne (MWh),Niveau de vie median
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215,13.6,13.7,4.395064,24030.0
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121,10.8,9.8,5.073961,20990.0
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345,10.4,11.0,3.696739,21450.0
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892,9.6,9.7,3.434983,21140.0
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480,11.3,11.9,4.125586,21790.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,34.5,3313.000,12.0,13.0,1.883515,18000.0
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676,12.0,13.0,1.688178,19200.0
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,53.0,2252.000,13.0,14.0,1.125110,11000.0
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656,10.0,12.0,1.474097,16520.0
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,77.0,1274.000,13.0,13.0,0.666353,9000.0

In [68]:
faj_df.columns = ["budge_dep","montant_distribue","nombre_aides","montant_moy","nb_benef","cohabit","pop_etud","taux_pauvr","etud_pauvr","loyer_moy_appart", "loyer_moy_mais", "conso_ener","niveau_vie"]

In [69]:
faj_df

,budge_dep,montant_distribue,nombre_aides,montant_moy,nb_benef,cohabit,pop_etud,taux_pauvr,etud_pauvr,loyer_moy_appart,loyer_moy_mais,conso_ener,niveau_vie
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215,13.6,13.7,4.395064,24030.0
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121,10.8,9.8,5.073961,20990.0
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345,10.4,11.0,3.696739,21450.0
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892,9.6,9.7,3.434983,21140.0
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480,11.3,11.9,4.125586,21790.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,34.5,3313.000,12.0,13.0,1.883515,18000.0
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676,12.0,13.0,1.688178,19200.0
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,53.0,2252.000,13.0,14.0,1.125110,11000.0
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656,10.0,12.0,1.474097,16520.0
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,77.0,1274.000,13.0,13.0,0.666353,9000.0

In [70]:
model = statsmodels.formula.api.ols('etud_pauvr ~ budge_dep + montant_distribue + nombre_aides + montant_moy + nb_benef + cohabit + loyer_moy_appart + conso_ener + niveau_vie', data = faj_df)
result = model.fit()

result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             etud_pauvr   R-squared:                       0.817
Model:                            OLS   Adj. R-squared:                  0.794
Method:                 Least Squares   F-statistic:                     34.74
Date:                Mon, 18 Nov 2024   Prob (F-statistic):           2.06e-22
Time:                        09:42:06   Log-Likelihood:                -760.11
No. Observations:                  80   AIC:                             1540.
Df Residuals:                      70   BIC:                             1564.
Df Model:                           9
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          5336.6251   5926.495      0.900      0.371   -6483.396    1.72e+04
budge_dep            -0.0014      0.002     -0.927      0.357      -0.004       0.002
montant_distribue     0.0198      0.006      3.166      0.002       0.007       0.032
nombre_aides         -1.9186      0.725     -2.647      0.010      -3.364      -0.473
montant_moy         -12.1262      7.584     -1.599      0.114     -27.252       3.000
nb_benef              0.3243      1.755      0.185      0.854      -3.176       3.824
cohabit            -234.9917     52.725     -4.457      0.000    -340.148    -129.835
loyer_moy_appart   1880.9156    171.182     10.988      0.000    1539.504    2222.327
conso_ener          475.2285    726.140      0.654      0.515    -973.013    1923.470
niveau_vie           -0.7043      0.300     -2.350      0.022      -1.302      -0.106
==============================================================================
Omnibus:                       18.138   Durbin-Watson:                   1.811
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               31.452
Skew:                           0.848   Prob(JB):                     1.48e-07
Kurtosis:                       5.561   Cond. No.                     1.06e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.06e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""