# Main imports

In [6]:
import os
import pandas as pd 
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np
from tqdm import tqdm
from collections import defaultdict
import numpy as np


pd.options.display.max_columns = 200
pd.options.display.max_rows = 50

# Load FAJ 2015 2020

In [7]:
path_df = "../database/cleaned/cleaned_faj2015_2020.csv"

faj_df = pd.read_csv(path_df, index_col=0)

In [8]:
faj_df

,Budget FAJ (en euros),Montant des aides individuelles attribuées (en euros),Nombre d'aides individuelles attribuées (2),Montant moyen de l'aide individuelle attribuée (en euros),Nombre de bénéficiaires du FAJ,Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %,Population étudiante,Taux pauvreté département,Population étudiante sous le seuil de pauvreté
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480
...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,NaN,0.000
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,NaN,0.000
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,NaN,0.000

# Cost rent

In [9]:
path_df = "../database/cleaned/cleaned_rent_cost_student.csv"

cost_rent_df = pd.read_csv(path_df, index_col=0)

In [10]:
for i in faj_df.index:
    if i not in cost_rent_df.index:
        print('Dieu', i)

In [ ]:
for i in faj_df.index:
    if i not in cost_rent_df.index:
        print('Dieu', i)

In [24]:
cost_rent_df.loc["Ain",["Loyer m2 moyen\r appartement","Loyer m2 moyen\r maison"]][0]

/tmp/ipykernel_11065/2615587039.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cost_rent_df.loc["Ain",["Loyer m2 moyen\r appartement","Loyer m2 moyen\r maison"]][0]

np.float64(13.6)

In [35]:
cost_arr_appartement = []
cost_arr_maison = []

for i in faj_df.index:
    if i in cost_rent_df.index:
        cost_arr_appartement.append(cost_rent_df.loc[i,["Loyer m2 moyen\r appartement"]].values[0])
        cost_arr_maison.append(cost_rent_df.loc[i,["Loyer m2 moyen\r maison"]].values[0])
    else:
        cost_arr_appartement.append(np.nan)
        cost_arr_maison.append(np.nan)

In [36]:
cost_arr_appartement
cost_arr_maison

[np.float64(13.7),
 np.float64(9.8),
 np.float64(11.0),
 np.float64(9.7),
 np.float64(11.9),
 np.float64(13.4),
 np.float64(10.8),
 np.float64(9.8),
 np.float64(10.7),
 np.float64(15.0),
 np.float64(13.2),
 np.float64(18.4),
 np.float64(11.6),
 np.float64(12.4),
 np.float64(11.3),
 np.float64(9.7),
 np.float64(9.7),
 np.float64(10.2),
 np.float64(10.6),
 np.float64(12.1),
 np.float64(10.2),
 np.float64(11.1),
 np.float64(11.5),
 np.float64(11.8),
 np.float64(9.8),
 np.float64(11.8),
 np.float64(9.0),
 np.float64(11.2),
 np.float64(10.0),
 np.float64(11.5),
 np.float64(13.9),
 np.float64(14.0),
 np.float64(9.5),
 np.float64(10.6),
 np.float64(11.0),
 np.float64(9.2),
 np.float64(11.3),
 np.float64(9.3),
 np.float64(11.7),
 np.float64(12.3),
 np.float64(13.3),
 np.float64(10.0),
 np.float64(10.1),
 np.float64(11.2),
 np.float64(13.2),
 np.float64(10.8),
 np.float64(10.5),
 np.float64(28.4),
 np.float64(16.0),
 np.float64(20.1),
 np.float64(18.4),
 np.float64(28.5),
 np.float64(20.7),
 np.float64(23.4),
 np.float64(19.4),
 np.float64(12.0),
 np.float64(11.8),
 np.float64(10.0),
 np.float64(9.2),
 np.float64(12.0),
 np.float64(9.6),
 np.float64(11.7),
 np.float64(9.9),
 np.float64(8.9),
 np.float64(9.9),
 np.float64(13.3),
 np.float64(11.8),
 np.float64(10.0),
 np.float64(12.9),
 np.float64(9.3),
 np.float64(9.8),
 np.float64(9.6),
 np.float64(9.7),
 np.float64(10.5),
 np.float64(10.3),
 np.float64(11.6),
 np.float64(12.5),
 np.float64(10.3),
 np.float64(12.7),
 np.float64(9.9),
 np.float64(9.7),
 np.float64(10.7),
 np.float64(11.1),
 np.float64(10.3),
 np.float64(10.7),
 np.float64(12.2),
 np.float64(10.6),
 np.float64(9.0),
 np.float64(9.5),
 np.float64(11.1),
 np.float64(11.4),
 np.float64(12.5),
 np.float64(19.8),
 np.float64(15.8),
 np.float64(15.0),
 np.float64(12.5),
 np.float64(13.0),
 np.float64(13.0),
 np.float64(14.0),
 np.float64(12.0),
 np.float64(13.0)]

In [38]:
faj_df["Loyer moyen m2 appartement"] = cost_arr_appartement
faj_df["Loyer moyen m2 maison"] = cost_arr_maison

In [39]:
faj_df

,Budget FAJ (en euros),Montant des aides individuelles attribuées (en euros),Nombre d'aides individuelles attribuées (2),Montant moyen de l'aide individuelle attribuée (en euros),Nombre de bénéficiaires du FAJ,Part de l'ensemble des jeunes de 20 à 24 ans vivant chez les parents en %,Population étudiante,Taux pauvreté département,Population étudiante sous le seuil de pauvreté,Loyer moyen m2 appartement,Loyer moyen m2 maison
Ain,457200.00,252328.00,1520.0,166.01,971.0,55.59,3183.0,10.5,334.215,13.6,13.7
Allier,198034.00,147222.06,1397.0,105.38,778.0,40.77,3857.0,15.3,590.121,10.8,9.8
Ardèche,271930.93,152403.00,1203.0,126.69,694.0,53.46,1415.0,14.3,202.345,10.4,11.0
Cantal,108000.00,32147.30,195.0,164.86,155.0,42.94,1431.0,13.2,188.892,9.6,9.7
Drôme,505023.39,196800.26,891.0,220.88,845.0,51.33,7920.0,14.4,1140.480,11.3,11.9
...,...,...,...,...,...,...,...,...,...,...,...
Guadeloupe,380267.34,344722.03,1661.0,207.54,616.0,70.90,9603.0,NaN,0.000,12.0,13.0
Martinique,355000.00,NaN,704.0,NaN,704.0,73.64,8628.0,26.7,2303.676,12.0,13.0
Guyane,255074.04,234381.00,490.0,478.33,490.0,50.97,4250.0,NaN,0.000,13.0,14.0
La Réunion,400000.00,211471.15,1152.0,183.57,1019.0,60.64,21426.0,35.6,7627.656,10.0,12.0
Mayotte,NaN,NaN,NaN,NaN,NaN,NaN,1655.0,NaN,0.000,13.0,13.0

# Save merged df

In [41]:
path_merged = "../database/cleaned/merged_faj2015_2020.csv"
faj_df.to_csv(path_merged)